question_data = [
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Politics",
     "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in "
                 "1912.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Dihydrogen Monoxide is a dangerous chemical.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
                                      "question": "Stephen Chbosky wrote the book &#039;The Perks of Being A Wallflower&#039;.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In the Super Mario series, the character Pauline is a Princess like Princess Peach.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "Korean girl group, TWICE, consists of 9 members", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
                                       "question": "Hungary is the only country in the world beginning with H.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals",
     "question": "Rabbits can see what&#039;s behind themselves without turning their heads.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                       "question": "The music group Daft Punk got their name from a negative review they recieved.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "The Republic of Malta is the smallest microstate worldwide.", "correct_answer": "False",
     "incorrect_answers": ["True"]}
]
